import type { ChangedFile } from '../types.js';

/**
 * File selection.
 *
 * Triage is a false economy. A strong reviewer reads essentially 100% of
 * source files, 99% of tests and 71% of config. It does not triage the diff — it
 * only drops files with no reviewable semantics. So this module is a *filter*,
 * not a ranker, and it errs towards including.
 */

export interface Selection {
  selected: ChangedFile[];
  skipped: { path: string; reason: string }[];
}

/** Compile a glob into an anchored RegExp. `**` crosses separators, `*` does not. */
export function globToRegExp(glob: string): RegExp {
  let out = '';
  for (let i = 0; i < glob.length; i++) {
    const c = glob[i]!;
    if (c === '*') {
      if (glob[i + 1] === '*') {
        i++;
        if (glob[i + 1] === '/') { i++; out += '(?:.*/)?'; } else { out += '.*'; }
      } else {
        out += '[^/]*';
      }
    } else if (c === '?') {
      out += '[^/]';
    } else if ('.+^${}()|[]\\/'.includes(c)) {
      out += `\\${c}`;
    } else {
      out += c;
    }
  }
  return new RegExp(`^${out}$`);
}

const GENERATED_MARKERS = ['@generated', 'DO NOT EDIT', 'Code generated by', 'auto-generated'];

/** Binary-ish or machine-written content has no review value. */
function inherentlyUnreviewable(f: ChangedFile): string | null {
  if (f.status === 'removed') return 'file deleted';
  if (!f.patch) return 'no textual diff (binary or too large)';
  if (f.additions + f.deletions === 0) return 'no line changes';

  const head = f.patch.slice(0, 2000);
  if (GENERATED_MARKERS.some((m) => head.includes(m))) return 'generated file';

  // A diff whose added lines are enormous is a bundle, lockfile or minified blob.
  const longest = f.patch
    .split('\n')
    .filter((l) => l.startsWith('+'))
    .reduce((n, l) => Math.max(n, l.length), 0);
  if (longest > 2000) return 'minified or bundled content';

  return null;
}

export function selectFiles(files: ChangedFile[], pathFilters: string[]): Selection {
  const denies = pathFilters
    .filter((p) => p.startsWith('!'))
    .map((p) => ({ glob: p, re: globToRegExp(p.slice(1)) }));
  const allows = pathFilters
    .filter((p) => !p.startsWith('!'))
    .map((p) => ({ glob: p, re: globToRegExp(p) }));

  const selected: ChangedFile[] = [];
  const skipped: { path: string; reason: string }[] = [];

  for (const f of files) {
    const deny = denies.find((d) => d.re.test(f.path));
    if (deny) { skipped.push({ path: f.path, reason: `path filter ${deny.glob}` }); continue; }
    if (allows.length && !allows.some((a) => a.re.test(f.path))) {
      skipped.push({ path: f.path, reason: 'not matched by any path filter' });
      continue;
    }
    const why = inherentlyUnreviewable(f);
    if (why) { skipped.push({ path: f.path, reason: why }); continue; }
    selected.push(f);
  }
  return { selected, skipped };
}

/** Line numbers in the new file that the diff actually touches. */
export function addedLineNumbers(patch: string): number[] {
  const out: number[] = [];
  let line = 0;
  for (const raw of patch.split('\n')) {
    const hunk = /^@@ -\d+(?:,\d+)? \+(\d+)(?:,(\d+))? @@/.exec(raw);
    if (hunk) { line = Number(hunk[1]); continue; }
    if (raw.startsWith('+') && !raw.startsWith('+++')) { out.push(line); line++; continue; }
    if (raw.startsWith('-') || raw.startsWith('\\')) continue;
    line++;
  }
  return out;
}

/**
 * Group files the way a reviewer would describe them — this drives the
 * walkthrough table and keeps related files together.
 */
export function groupFiles(files: ChangedFile[]): Map<string, ChangedFile[]> {
  const groups = new Map<string, ChangedFile[]>();
  for (const f of files) {
    const seg = f.path.split('/');
    const key =
      (seg[0] === 'apps' || seg[0] === 'packages') && seg.length > 2
        ? `${seg[0]}/${seg[1]}`
        : seg.length > 1
          ? seg.slice(0, Math.min(2, seg.length - 1)).join('/')
          : '.';
    const list = groups.get(key);
    if (list) list.push(f);
    else groups.set(key, [f]);
  }
  return groups;
}

/**
 * Pair a test file with the source it covers, and vice versa.
 * A change and its test are the most common pair that must agree with each other.
 */
export function testCounterparts(path: string): string[] {
  const asSource = path.replace(/\.(test|spec)\.([cm]?[jt]sx?)$/, '.$2');
  if (asSource !== path) {
    return [
      asSource,
      asSource.replace('/__tests__/', '/'),
      asSource.replace('/tests/', '/src/'),
    ];
  }
  const ext = /\.([cm]?[jt]sx?)$/.exec(path)?.[1];
  if (!ext) return [];
  const stem = path.slice(0, -(ext.length + 1));
  return [`${stem}.test.${ext}`, `${stem}.spec.${ext}`];
}
